export const yearsOfExperience = 3;

export const person = {
  name: 'Subhamay Dhara',
  initials: 'SD',
  tagline: 'Driven to bridge technology, business, and people to transform ideas into impactful, customer-centric products.',
  headline: 'I build enterprise software that actually ships.',
  bio: `Software Engineer with ${yearsOfExperience}+ years at a global MNC. I've shipped solutions contributing to ~50% of product features, achieved ~95% integration-test coverage, supported 20+ releases, and resolved 9+ customer issues. Skilled in Salesforce, Apex, LWC, APIs, automation, and AI-driven development.`,
  bioExtended: `My work sits at the intersection of business requirements and technical architecture. I translate complex stakeholder needs into scalable solutions — whether that means modeling a Revenue Lifecycle flow in Salesforce CPQ, designing a Puppeteer–Jest test suite from scratch, or integrating enterprise PLM data through REST APIs. I was recognized with the Innovation Excellence Award at Global MNC (Digital Industries) for contributions to an award-winning Salesforce–Teamcenter integration.`,
  location: 'Maharashtra, India',
  email: 'subhamaydhara86@gmail.com',
  github: 'https://github.com/dharasubhamay',
  linkedin: 'https://linkedin.com/in/subhamay-dhara',
  website: 'https://dharasubhamay.github.io',
};

export const experience = [
  {
    role: 'Software Engineer',
    company: 'Global MNC (Digital Industries)',
    type: 'Full-time',
    from: 'Jul 2023',
    to: 'Present',
    location: 'Maharashtra, India',
    summary: 'Building enterprise Salesforce solutions and integration products at the intersection of Asset Management, Service Lifecycle, and Revenue Lifecycle Management.',
    bullets: [
      'Contributed to ~50% of product feature development on an award-winning Salesforce–Teamcenter PLM integration solution.',
      'Translated complex business requirements into scalable LWC/Apex solutions and API-driven microservices, supporting 20+ deployments.',
      'Designed and built a zero-cost Puppeteer–Jest automation framework covering ~95% of integration tests from scratch.',
      'Resolved 9+ customer issues while collaborating with 25+ cross-functional stakeholders across the full SDLC.',
      'Applied BMAD Method (Agile AI-Driven Development) for requirement analysis, solution design, code review, and testing.',
    ],
    tags: ['Salesforce LWC', 'Apex', 'Salesforce CPQ', 'Revenue Cloud', 'REST APIs', 'Node.js', 'Puppeteer', 'Jest', 'JavaScript', 'SOQL', 'Git'],
  },
  {
    role: 'Data Science Intern',
    company: 'Innomatics Research Labs',
    type: 'Internship',
    from: 'Jan 2023',
    to: 'Mar 2023',
    location: 'Remote',
    summary: 'Worked on data science projects involving data analysis, visualization, and machine learning techniques.',
    bullets: [
      'Applied data analysis and visualization techniques to derive insights from datasets.',
      'Built and evaluated machine learning models for classification and prediction tasks.',
      'Gained hands-on experience with the end-to-end data science workflow.',
    ],
    tags: ['Python', 'Data Science', 'Machine Learning', 'Data Analysis'],
  },
  {
    role: 'Software Developer Intern',
    company: 'Global MNC (Digital Industries)',
    type: 'Internship',
    from: 'Jul 2022',
    to: 'Sep 2022',
    location: 'Maharashtra, India',
    summary: 'Built full-stack enterprise application features during a 3-month internship, focusing on localization infrastructure.',
    bullets: [
      'Developed RESTful Web APIs for translation and localization capabilities across multiple projects.',
      'Built a Locale Management System to simplify multilingual support for developers.',
      'Integrated frontend (Angular) and backend (ASP.NET Core) application layers.',
    ],
    tags: ['Angular', 'ASP.NET Core', 'RESTful API', 'TypeScript', 'C#'],
  },
  {
    role: 'TPO Student Representative',
    company: 'GCETTB',
    type: 'Volunteering',
    from: 'Aug 2022',
    to: 'Nov 2022',
    location: 'West Bengal, India',
    summary: 'Served as the Training and Placement Officer student representative for the CSE 2023 batch, bridging students and placement cell.',
    bullets: [
      'Coordinated between the placement cell and CSE final-year students for campus recruitment activities.',
      'Facilitated communication around placement drives, schedules, and company requirements.',
      'Supported students with placement preparation and documentation.',
    ],
    tags: ['Leadership', 'Coordination', 'Campus Recruitment'],
  },
  {
    role: 'Chapter President',
    company: 'CodeChef GCETTB Chapter',
    type: 'Leadership',
    from: 'Sep 2021',
    to: '2022',
    location: 'West Bengal, India',
    summary: 'Founded and led the college CodeChef chapter, building a community of competitive programmers from the ground up.',
    bullets: [
      'Founded the CodeChef chapter at the college level — first of its kind in the institution.',
      'Organized coding contests, workshops, and peer learning sessions to grow the competitive programming community.',
      'Mentored junior students in data structures, algorithms, and competitive programming.',
    ],
    tags: ['Leadership', 'Competitive Programming', 'Community Building', 'Mentorship'],
  },
  {
    role: 'Software Developer Intern',
    company: 'Global MNC (Digital Industries)',
    type: 'Internship',
    from: 'Jun 2021',
    to: 'Aug 2021',
    location: 'Maharashtra, India',
    summary: 'Completed a 3-month software development internship, gaining exposure to enterprise software engineering practices.',
    bullets: [
      'Worked on enterprise software development tasks under mentorship from senior engineers.',
      'Gained foundational exposure to industrial-scale software development workflows and tools.',
    ],
    tags: ['Software Development', 'Enterprise Systems'],
  },
  {
    role: 'Education Volunteer',
    company: 'Helping Hand Katjunagar',
    type: 'Volunteering',
    from: '2021',
    to: '2021',
    location: 'West Bengal, India',
    summary: 'Volunteered to provide education support to underprivileged students in the local community.',
    bullets: [
      'Taught and mentored students from underprivileged backgrounds as part of a community education initiative.',
      'Contributed to bridging the educational gap through regular volunteering sessions.',
    ],
    tags: ['Volunteering', 'Education', 'Community Service'],
  },
  {
    role: 'Robotics Intern',
    company: 'Internship Studio',
    type: 'Internship',
    from: 'Jun 2021',
    to: 'Jul 2021',
    location: 'Remote',
    summary: 'Completed a 2-month robotics internship, learning foundational robotics concepts and automation principles.',
    bullets: [
      'Explored robotics fundamentals including sensors, actuators, and control systems.',
      'Worked on automation tasks and robotics programming exercises.',
    ],
    tags: ['Robotics', 'Automation', 'Python'],
  },
  {
    role: 'Data Science & Business Analytics Intern',
    company: 'The Sparks Foundation',
    type: 'Internship',
    from: 'Jun 2021',
    to: 'Jun 2021',
    location: 'Remote',
    summary: 'Completed a task-based internship focused on data science and business analytics with The Sparks Foundation (GRIP).',
    bullets: [
      'Completed data science and business analytics tasks as part of the GRIP internship program.',
      'Applied analytical techniques to real-world datasets and presented findings.',
    ],
    tags: ['Python', 'Data Science', 'Business Analytics', 'Data Visualization'],
  },
  {
    role: 'Class Representative',
    company: 'GCETTB',
    type: 'Volunteering',
    from: '2019',
    to: '2023',
    location: 'West Bengal, India',
    summary: 'Served as Class Representative for the CSE 2023 batch throughout the 4-year B.Tech program.',
    bullets: [
      'Represented the CSE batch in academic and administrative matters for 4 consecutive years.',
      'Coordinated between faculty and students on scheduling, feedback, and institutional activities.',
      'Fostered a collaborative class environment and resolved student grievances.',
    ],
    tags: ['Leadership', 'Representation', 'Communication'],
  },
  {
    role: 'Excel Automation Intern',
    company: 'Internship Studio',
    type: 'Internship',
    from: 'Jun 2020',
    to: 'Aug 2020',
    location: 'Remote',
    summary: 'Completed a 3-month internship focused on Excel automation and VBA scripting for business productivity tasks.',
    bullets: [
      'Built automation scripts using Excel VBA to streamline repetitive business workflows.',
      'Developed spreadsheet-based tools to improve reporting and data processing efficiency.',
    ],
    tags: ['Excel', 'VBA', 'Automation', 'Scripting'],
  },
];

export const projects = [
  {
    title: 'Salesforce–Teamcenter Integration',
    summary: 'Award-winning enterprise integration · Salesforce + PLM',
    description: 'Enterprise-grade integration connecting Salesforce with Teamcenter PLM, enabling Service Excellence for Asset Management, Service Lifecycle Management, and Revenue Lifecycle Management. Implemented asynchronous processing, permission-based access, notifications, and localization — contributing to ~50% of product feature development and earning the Innovation Excellence Award.',
    tags: ['Salesforce LWC', 'Apex', 'Salesforce CPQ', 'Revenue Cloud', 'REST APIs', 'Node.js', 'SOQL', 'SOSL', 'GitLab CI/CD'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: 'Innovation Excellence Award',
    impact: [
      'Core contributor (~50% of product feature development) on an award-winning product.',
      'Delivered 20+ production releases with async processing, permission-based access controls, and localization.',
      'Recognized with the Innovation Excellence Award for engineering contributions.',
    ],
  },
  {
    title: 'Puppeteer–Jest Automation Framework',
    summary: 'Zero-cost integration testing at scale',
    description: 'A custom automation testing framework built from scratch using Puppeteer and Jest, designed for Salesforce integration testing in CI/CD environments. Sole designer and developer — went from zero coverage to ~95% integration test coverage, strengthening regression efficiency, product reliability, and release confidence.',
    tags: ['Puppeteer', 'Jest', 'Node.js', 'JavaScript', 'GitLab CI/CD', 'Automated Testing'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      '~95% integration test coverage achieved from zero — sole designer and developer.',
      'Zero licensing cost — built entirely with open-source tools.',
      'Integrated into GitLab CI/CD pipeline for automated regression on every release.',
    ],
  },
  {
    title: 'Salesforce Revenue Cloud & CPQ',
    summary: 'Revenue Lifecycle Management Solutions · Enterprise Salesforce',
    description: 'Developed Salesforce Revenue Cloud and CPQ capabilities to support revenue lifecycle management, translating complex business requirements into scalable, production-ready solutions across the enterprise platform.',
    tags: ['Salesforce LWC', 'Apex', 'Salesforce CPQ', 'Revenue Cloud', 'SOQL', 'SOSL'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Built solutions using LWC, Apex, CPQ and Revenue Cloud.',
      'Implemented complex business logic and permission-based access.',
      'Supported localization, notifications and asynchronous processing.',
      'Contributed across 20+ deployments/releases.',
    ],
  },
  {
    title: 'Microservices & API Integration',
    summary: 'API-Driven Microservices Architecture · Scalable enterprise integration',
    description: 'Designed and implemented API-driven microservices to extend Salesforce capabilities and integrate enterprise systems, using asynchronous processing and REST-based communication for scalable service workflows.',
    tags: ['Node.js', 'REST APIs', 'Microservices', 'JavaScript', 'Salesforce'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Developed Node.js and REST API integrations.',
      'Implemented asynchronous processing for scalable workflows.',
      'Connected Salesforce with external enterprise applications.',
      'Supported production deployments and troubleshooting.',
    ],
  },
  {
    title: 'End-to-End Engineering Ownership',
    summary: 'From Requirements to Production Support · Full SDLC ownership',
    description: 'Contributed across the complete software development lifecycle, from requirements analysis and architecture through implementation, CI/CD, deployment, and production support.',
    tags: ['Agile/Scrum', 'GitLab CI/CD', 'Git', 'SDLC', 'Salesforce'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Collaborated with 25+ cross-functional stakeholders.',
      'Resolved 9+ customer issues across production environments.',
      'Participated in architecture, development, code reviews and testing.',
      'Supported 20+ deployments/releases.',
    ],
  },
  {
    title: 'BMAD-Driven AI Development',
    summary: 'BMAD Method for AI-Assisted Software Development · Streamlining the SDLC',
    description: 'Applied the BMAD Method (Breakthrough Method for Agile AI-Driven Development) across the software development lifecycle to structure AI-assisted engineering workflows from requirements through testing.',
    tags: ['BMAD Method', 'Agile/Scrum', 'AI-Driven Development'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Applied BMAD during requirements analysis and solution design.',
      'Used the methodology during implementation and code review.',
      'Incorporated AI-driven practices into testing and delivery workflows.',
      'Focused on improving development efficiency and delivery consistency.',
    ],
  },
  {
    title: 'Marketology',
    summary: 'Job seeker & service provider marketplace',
    description: 'Full-stack web marketplace connecting job seekers, service providers, and customers. Users can advertise jobs, services, and products, and discover offerings based on location — enhancing discovery opportunity by ~50%. Built with interactive social-style features combining job and service discovery in one platform.',
    tags: ['Angular', 'Bootstrap', 'ASP.NET Core', 'C#', 'SQL Server'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Location-based discovery enhanced match opportunity by ~50%.',
      'Combined job listing, service advertising, and social interaction in a single platform.',
      'Full-stack implementation as lead developer — Angular frontend, ASP.NET Core backend, SQL Server.',
    ],
  },
  {
    title: 'Pointo — Appointment Management System',
    summary: 'Covid-era RT-PCR appointment platform built as a team',
    description: 'During the Covid-19 pandemic, employees at companies were required to take RT-PCR tests — but standing in queues created gatherings and disrupted work schedules. Built as part of a 4-member team, Pointo is a web-based appointment system that lets employees book test slots in their free time. Admins can configure flexible days, times, and counters for each test period. I implemented the Admin Dashboard: total appointment views per test period and per day, employee management (add/remove), and appointment deletion.',
    tags: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
    links: [] as { label: string; href: string }[],
    featured: true,
    award: undefined,
    impact: [
      'Reduced queue gatherings during Covid-19 by enabling pre-scheduled RT-PCR appointments.',
      'Admin Dashboard gives full visibility — appointments by test period and by day.',
      'Flexible configuration: admins set available days, times, and counters per test period.',
    ],
  },
];

export const skills = [
  {
    category: 'Salesforce Platform',
    items: ['Salesforce LWC', 'Apex', 'Salesforce CPQ', 'Revenue Cloud', 'SOQL', 'SOSL', 'Platform Events', 'Asset Management', 'Service Lifecycle Management', 'Revenue Lifecycle Management', 'Async Processing', 'Localization'],
  },
  {
    category: 'Languages',
    items: ['JavaScript', 'TypeScript', 'Python', 'C#', 'Java', 'SQL', 'Apex', 'C++', 'C', 'PHP', 'MATLAB'],
  },
  {
    category: 'Frontend',
    items: ['React', 'Angular', 'LWC', 'HTML', 'CSS', 'Tailwind CSS', 'Bootstrap'],
  },
  {
    category: 'Backend & APIs',
    items: ['Node.js', 'ASP.NET Core', 'REST APIs', 'Express', 'Microservices'],
  },
  {
    category: 'Testing & DevOps',
    items: ['Puppeteer', 'Jest', 'GitLab CI/CD', 'Git', 'GitHub', 'Postman', 'Automated Testing'],
  },
  {
    category: 'Databases',
    items: ['SQL Server', 'MySQL', 'MongoDB', 'SQLite'],
  },
  {
    category: 'Cloud & Tools',
    items: ['Google Cloud', 'Excel', 'VBA', 'Data Analysis', 'Data Visualization'],
  },
];

export const achievements = [
  {
    year: '2024',
    title: 'Innovation Excellence Award',
    org: 'Global MNC (Digital Industries)',
    description: 'Recognized for contributions to the award-winning Salesforce–Teamcenter integration solution.',
  },
  {
    year: '2023',
    title: 'Student of the Year',
    org: 'B.Tech CSE — CGPA 9.52',
    description: 'Top-ranked graduate of the 2023 CSE batch. Recognized for academic and leadership excellence.',
  },
  {
    year: '2018',
    title: 'Student of the Year',
    org: 'Higher Secondary Education',
    description: 'Recognized as Student of the Year for academic excellence in higher secondary education.',
  },
  {
    year: '2020',
    title: 'Siemens Scholarship',
    org: 'Siemens India',
    description: 'Selected among 150 students across India for academic merit in engineering.',
  },
  {
    year: '2021',
    title: 'CodeChef Chapter President',
    org: 'CodeChef GCETTB Chapter',
    description: 'Founded and led the college CodeChef chapter, building a community of competitive programmers.',
  },
];
